// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextNuvem.Infra.Data.Context;

#nullable disable

namespace TextNuvem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504145215_UpdateCustomer")]
    partial class UpdateCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangesDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastProjectIdUpdate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("LastProjectIdUpdate")
                        .IsUnique()
                        .HasFilter("[LastProjectIdUpdate] IS NOT NULL");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Folders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.HasOne("TextNuvem.Domain.BackOffice.Entities.Project", "LastProjectUpdate")
                        .WithOne()
                        .HasForeignKey("TextNuvem.Domain.BackOffice.Entities.Customer", "LastProjectIdUpdate")
                        .HasConstraintName("FK_Customer_LastProjectUpdateId");

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Email");

                            b1.HasKey("CustomerId");

                            b1.HasIndex(new[] { "Address" }, "IX_Customer_Email")
                                .IsUnique();

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HashPassword")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("HashPassword");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("Expired")
                                .HasColumnType("DATETIME2")
                                .HasColumnName("ExpiredRefreshToken");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT")
                                .HasColumnName("RefreshToken");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LastProjectUpdate");

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Project", b =>
                {
                    b.HasOne("TextNuvem.Domain.BackOffice.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
