// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextNuvem.Domain.BackOffice.ValueObject;
using TextNuvem.Infra.Data.Context;

#nullable disable

namespace TextNuvem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<ChangesDate>>("ChangesDate")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LastProjectIdUpdate")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LastProjectIdUpdate")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Folders")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.HasOne("TextNuvem.Domain.BackOffice.Entities.Project", "LastProjectUpdate")
                        .WithOne()
                        .HasForeignKey("TextNuvem.Domain.BackOffice.Entities.Customer", "LastProjectIdUpdate")
                        .HasConstraintName("fk_customer_last_project_update_id");

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId");

                            b1.HasIndex(new[] { "Address" }, "ix_customer_email")
                                .IsUnique();

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HashPassword")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("hash_password");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TextNuvem.Domain.BackOffice.ValueObject.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Expired")
                                .HasColumnType("timestamptz")
                                .HasColumnName("expired_refresh_token");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT")
                                .HasColumnName("refresh_token");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LastProjectUpdate");

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Project", b =>
                {
                    b.HasOne("TextNuvem.Domain.BackOffice.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TextNuvem.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
